FROM node:22-alpine AS develop

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .
RUN npm run build

FROM node:22-alpine

WORKDIR /app

COPY package*.json ./ 

COPY --from=develop /app/dist ./dist
COPY --from=develop /app/doc ./doc

RUN  npm ci --omit=dev && npm cache clean --force && rm -rf src

CMD ["npm", "run", "start:prod"]